# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_korm.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore
from PyQt5 import QtGui
from PyQt5 import QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_Dialog_Korm(object):
    def setupUi(self, Dialog_Korm):
        Dialog_Korm.setObjectName(_fromUtf8("Dialog_Korm"))
        Dialog_Korm.resize(942, 706)
        self.groupBox_2 = QGroupBox(Dialog_Korm)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 941, 271))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.savebankabtn = QtWidgets.QPushButton(self.groupBox_2)
        self.savebankabtn.setGeometry(QtCore.QRect(750, 230, 112, 31))
        self.savebankabtn.setObjectName(_fromUtf8("savebankabtn"))
        self.labelbanka2 = QtWidgets.QLabel(self.groupBox_2)
        self.labelbanka2.setGeometry(QtCore.QRect(180, 42, 81, 16))
        self.labelbanka2.setObjectName(_fromUtf8("labelbanka2"))
        self.labelbanka6 = QtWidgets.QLabel(self.groupBox_2)
        self.labelbanka6.setGeometry(QtCore.QRect(840, 40, 81, 16))
        self.labelbanka6.setObjectName(_fromUtf8("labelbanka6"))
        self.labelbanka4 = QtWidgets.QLabel(self.groupBox_2)
        self.labelbanka4.setGeometry(QtCore.QRect(500, 40, 91, 16))
        self.labelbanka4.setObjectName(_fromUtf8("labelbanka4"))
        self.labelbanka1 = QtWidgets.QLabel(self.groupBox_2)
        self.labelbanka1.setGeometry(QtCore.QRect(20, 42, 81, 16))
        self.labelbanka1.setObjectName(_fromUtf8("labelbanka1"))
        self.labelbanka5 = QtWidgets.QLabel(self.groupBox_2)
        self.labelbanka5.setGeometry(QtCore.QRect(670, 40, 101, 16))
        self.labelbanka5.setObjectName(_fromUtf8("labelbanka5"))
        self.labelbanka3 = QtWidgets.QLabel(self.groupBox_2)
        self.labelbanka3.setGeometry(QtCore.QRect(340, 41, 91, 16))
        self.labelbanka3.setObjectName(_fromUtf8("labelbanka3"))
        self.banka3 = QtWidgets.QLabel(self.groupBox_2)
        self.banka3.setGeometry(QtCore.QRect(340, 60, 66, 161))
        self.banka3.setText(_fromUtf8(""))
        self.banka3.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.banka3.setObjectName(_fromUtf8("banka3"))
        self.banka5 = QtWidgets.QLabel(self.groupBox_2)
        self.banka5.setGeometry(QtCore.QRect(670, 54, 66, 171))
        self.banka5.setText(_fromUtf8(""))
        self.banka5.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.banka5.setObjectName(_fromUtf8("banka5"))
        self.banka1 = QtWidgets.QLabel(self.groupBox_2)
        self.banka1.setGeometry(QtCore.QRect(20, 54, 51, 171))
        self.banka1.setText(_fromUtf8(""))
        self.banka1.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.banka1.setObjectName(_fromUtf8("banka1"))
        self.banka6 = QtWidgets.QLabel(self.groupBox_2)
        self.banka6.setGeometry(QtCore.QRect(840, 60, 66, 161))
        self.banka6.setText(_fromUtf8(""))
        self.banka6.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.banka6.setObjectName(_fromUtf8("banka6"))
        self.banka2 = QtWidgets.QLabel(self.groupBox_2)
        self.banka2.setGeometry(QtCore.QRect(180, 58, 66, 161))
        self.banka2.setText(_fromUtf8(""))
        self.banka2.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.banka2.setObjectName(_fromUtf8("banka2"))
        self.labelbanka4_2 = QtWidgets.QLabel(self.groupBox_2)
        self.labelbanka4_2.setGeometry(QtCore.QRect(515, 108, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.labelbanka4_2.setFont(font)
        self.labelbanka4_2.setObjectName(_fromUtf8("labelbanka4_2"))
        self.labelbanka5_2 = QtWidgets.QLabel(self.groupBox_2)
        self.labelbanka5_2.setGeometry(QtCore.QRect(685, 108, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.labelbanka5_2.setFont(font)
        self.labelbanka5_2.setObjectName(_fromUtf8("labelbanka5_2"))
        self.labelbanka6_2 = QtWidgets.QLabel(self.groupBox_2)
        self.labelbanka6_2.setGeometry(QtCore.QRect(857, 109, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.labelbanka6_2.setFont(font)
        self.labelbanka6_2.setObjectName(_fromUtf8("labelbanka6_2"))
        self.labelbanka3_2 = QtWidgets.QLabel(self.groupBox_2)
        self.labelbanka3_2.setGeometry(QtCore.QRect(356, 108, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.labelbanka3_2.setFont(font)
        self.labelbanka3_2.setObjectName(_fromUtf8("labelbanka3_2"))
        self.labelbanka1_2 = QtWidgets.QLabel(self.groupBox_2)
        self.labelbanka1_2.setGeometry(QtCore.QRect(35, 107, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.labelbanka1_2.setFont(font)
        self.labelbanka1_2.setObjectName(_fromUtf8("labelbanka1_2"))
        self.labelbanka2_2 = QtWidgets.QLabel(self.groupBox_2)
        self.labelbanka2_2.setGeometry(QtCore.QRect(196, 108, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.labelbanka2_2.setFont(font)
        self.labelbanka2_2.setObjectName(_fromUtf8("labelbanka2_2"))
        self.banka4 = QtWidgets.QLabel(self.groupBox_2)
        self.banka4.setGeometry(QtCore.QRect(500, 54, 66, 171))
        self.banka4.setText(_fromUtf8(""))
        self.banka4.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.banka4.setObjectName(_fromUtf8("banka4"))
        self.savebankabtn.raise_()
        self.labelbanka2.raise_()
        self.labelbanka6.raise_()
        self.labelbanka4.raise_()
        self.labelbanka1.raise_()
        self.labelbanka5.raise_()
        self.labelbanka3.raise_()
        self.banka3.raise_()
        self.banka1.raise_()
        self.labelbanka2_2.raise_()
        self.labelbanka1_2.raise_()
        self.labelbanka6_2.raise_()
        self.labelbanka5_2.raise_()
        self.banka6.raise_()
        self.labelbanka4_2.raise_()
        self.banka2.raise_()
        self.banka5.raise_()
        self.labelbanka3_2.raise_()
        self.banka4.raise_()
        self.banka3.raise_()
        self.banka5.raise_()
        self.banka1.raise_()
        self.banka6.raise_()
        self.banka2.raise_()
        self.labelbanka5_2.raise_()
        self.labelbanka6_2.raise_()
        self.labelbanka3_2.raise_()
        self.labelbanka1_2.raise_()
        self.labelbanka2_2.raise_()
        self.banka4.raise_()
        self.labelbanka4_2.raise_()
        self.groupBox = QGroupBox(Dialog_Korm)
        self.groupBox.setGeometry(QtCore.QRect(0, 270, 431, 431))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.editname = QtWidgets.QLineEdit(self.groupBox)
        self.editname.setGeometry(QtCore.QRect(20, 40, 391, 25))
        self.editname.setObjectName(_fromUtf8("editname"))
        self.btnaddzerno = QtWidgets.QPushButton(self.groupBox)
        self.btnaddzerno.setGeometry(QtCore.QRect(290, 250, 112, 34))
        self.btnaddzerno.setObjectName(_fromUtf8("btnaddzerno"))
        self.editdobavka = QtWidgets.QLineEdit(self.groupBox)
        self.editdobavka.setGeometry(QtCore.QRect(210, 300, 81, 25))
        self.editdobavka.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.editdobavka.setObjectName(_fromUtf8("editdobavka"))
        self.memo = QtWidgets.QTextEdit(self.groupBox)
        self.memo.setGeometry(QtCore.QRect(20, 90, 391, 141))
        self.memo.setObjectName(_fromUtf8("memo"))
        self.btnaddmaslo = QtWidgets.QPushButton(self.groupBox)
        self.btnaddmaslo.setGeometry(QtCore.QRect(125, 343, 112, 34))
        self.btnaddmaslo.setObjectName(_fromUtf8("btnaddmaslo"))
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 330, 66, 19))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 230, 66, 19))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.btnadddobavka = QtWidgets.QPushButton(self.groupBox)
        self.btnadddobavka.setGeometry(QtCore.QRect(290, 300, 112, 34))
        self.btnadddobavka.setObjectName(_fromUtf8("btnadddobavka"))
        self.editMaslo = QtWidgets.QLineEdit(self.groupBox)
        self.editMaslo.setGeometry(QtCore.QRect(20, 348, 101, 25))
        self.editMaslo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.editMaslo.setObjectName(_fromUtf8("editMaslo"))
        self.cancelbtn = QtWidgets.QPushButton(self.groupBox)
        self.cancelbtn.setGeometry(QtCore.QRect(20, 380, 112, 34))
        self.cancelbtn.setObjectName(_fromUtf8("cancelbtn"))
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 241, 19))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.combozerno = QtWidgets.QComboBox(self.groupBox)
        self.combozerno.setGeometry(QtCore.QRect(20, 250, 191, 25))
        self.combozerno.setObjectName(_fromUtf8("combozerno"))
        self.okbtn = QtWidgets.QPushButton(self.groupBox)
        self.okbtn.setGeometry(QtCore.QRect(290, 380, 112, 34))
        self.okbtn.setObjectName(_fromUtf8("okbtn"))
        self.combodobavka = QtWidgets.QComboBox(self.groupBox)
        self.combodobavka.setGeometry(QtCore.QRect(20, 300, 191, 25))
        self.combodobavka.setObjectName(_fromUtf8("combodobavka"))
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 70, 241, 19))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 280, 66, 19))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.editzerno = QtWidgets.QLineEdit(self.groupBox)
        self.editzerno.setGeometry(QtCore.QRect(210, 250, 81, 25))
        self.editzerno.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.editzerno.setObjectName(_fromUtf8("editzerno"))
        self.groupBox_3 = QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 0, 431, 431))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.editname_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.editname_2.setGeometry(QtCore.QRect(20, 40, 391, 25))
        self.editname_2.setObjectName(_fromUtf8("editname_2"))
        self.btnaddzerno_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.btnaddzerno_2.setGeometry(QtCore.QRect(290, 250, 112, 34))
        self.btnaddzerno_2.setObjectName(_fromUtf8("btnaddzerno_2"))
        self.editdobavka_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.editdobavka_2.setGeometry(QtCore.QRect(210, 300, 81, 25))
        self.editdobavka_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.editdobavka_2.setObjectName(_fromUtf8("editdobavka_2"))
        self.memo_2 = QtWidgets.QTextEdit(self.groupBox_3)
        self.memo_2.setGeometry(QtCore.QRect(20, 90, 391, 141))
        self.memo_2.setObjectName(_fromUtf8("memo_2"))
        self.btnaddmaslo_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.btnaddmaslo_2.setGeometry(QtCore.QRect(125, 343, 112, 34))
        self.btnaddmaslo_2.setObjectName(_fromUtf8("btnaddmaslo_2"))
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(20, 330, 66, 19))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(20, 230, 66, 19))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.btnadddobavka_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.btnadddobavka_2.setGeometry(QtCore.QRect(290, 300, 112, 34))
        self.btnadddobavka_2.setObjectName(_fromUtf8("btnadddobavka_2"))
        self.editMaslo_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.editMaslo_2.setGeometry(QtCore.QRect(20, 348, 101, 25))
        self.editMaslo_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.editMaslo_2.setObjectName(_fromUtf8("editMaslo_2"))
        self.cancelbtn_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.cancelbtn_2.setGeometry(QtCore.QRect(20, 380, 112, 34))
        self.cancelbtn_2.setObjectName(_fromUtf8("cancelbtn_2"))
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 241, 19))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.combozerno_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.combozerno_2.setGeometry(QtCore.QRect(20, 250, 191, 25))
        self.combozerno_2.setObjectName(_fromUtf8("combozerno_2"))
        self.okbtn_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.okbtn_2.setGeometry(QtCore.QRect(290, 380, 112, 34))
        self.okbtn_2.setObjectName(_fromUtf8("okbtn_2"))
        self.combodobavka_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.combodobavka_2.setGeometry(QtCore.QRect(20, 300, 191, 25))
        self.combodobavka_2.setObjectName(_fromUtf8("combodobavka_2"))
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(20, 70, 241, 19))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(20, 280, 66, 19))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.editzerno_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.editzerno_2.setGeometry(QtCore.QRect(210, 250, 81, 25))
        self.editzerno_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.editzerno_2.setObjectName(_fromUtf8("editzerno_2"))
        self.groupBox_4 = QGroupBox(Dialog_Korm)
        self.groupBox_4.setGeometry(QtCore.QRect(440, 270, 501, 431))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_6.setGeometry(QtCore.QRect(150, 230, 231, 22))
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(90, 180, 46, 13))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_2.setGeometry(QtCore.QRect(150, 110, 231, 22))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(90, 150, 46, 13))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(90, 90, 46, 13))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(90, 120, 46, 13))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_5.setGeometry(QtCore.QRect(150, 200, 231, 22))
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(90, 240, 46, 13))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_4.setGeometry(QtCore.QRect(150, 170, 231, 22))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_3.setGeometry(QtCore.QRect(150, 140, 231, 22))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(90, 210, 46, 13))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.comboBox_1 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_1.setGeometry(QtCore.QRect(150, 80, 231, 22))
        self.comboBox_1.setObjectName(_fromUtf8("comboBox_1"))

        self.retranslateUi(Dialog_Korm)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Korm)

    def retranslateUi(self, Dialog_Korm):
        Dialog_Korm.setWindowTitle(_translate("Dialog_Korm", "Dialog", None))
        self.groupBox_2.setTitle(_translate("Dialog_Korm", "Банки", None))
        self.savebankabtn.setText(_translate("Dialog_Korm", "Применить", None))
        self.labelbanka2.setText(_translate("Dialog_Korm", "TextLabel", None))
        self.labelbanka6.setText(_translate("Dialog_Korm", "TextLabel", None))
        self.labelbanka4.setText(_translate("Dialog_Korm", "TextLabel", None))
        self.labelbanka1.setText(_translate("Dialog_Korm", "TextLabel", None))
        self.labelbanka5.setText(_translate("Dialog_Korm", "TextLabel", None))
        self.labelbanka3.setText(_translate("Dialog_Korm", "TextLabel", None))
        self.labelbanka4_2.setText(_translate("Dialog_Korm", "4", None))
        self.labelbanka5_2.setText(_translate("Dialog_Korm", "5", None))
        self.labelbanka6_2.setText(_translate("Dialog_Korm", "6", None))
        self.labelbanka3_2.setText(_translate("Dialog_Korm", "3", None))
        self.labelbanka1_2.setText(_translate("Dialog_Korm", "1", None))
        self.labelbanka2_2.setText(_translate("Dialog_Korm", "2", None))
        self.groupBox.setTitle(_translate("Dialog_Korm", "Новый комбикорм", None))
        self.btnaddzerno.setText(_translate("Dialog_Korm", "Добавить", None))
        self.editdobavka.setText(_translate("Dialog_Korm", "0", None))
        self.btnaddmaslo.setText(_translate("Dialog_Korm", "Добавить", None))
        self.label.setText(_translate("Dialog_Korm", "Масло", None))
        self.label_4.setText(_translate("Dialog_Korm", "Зерно", None))
        self.btnadddobavka.setText(_translate("Dialog_Korm", "Добавить", None))
        self.editMaslo.setText(_translate("Dialog_Korm", "0", None))
        self.cancelbtn.setText(_translate("Dialog_Korm", "Отмена", None))
        self.label_5.setText(_translate("Dialog_Korm", "Название нового комбикорма", None))
        self.okbtn.setText(_translate("Dialog_Korm", "Применить", None))
        self.label_6.setText(_translate("Dialog_Korm", "Ингридиенты", None))
        self.label_3.setText(_translate("Dialog_Korm", "Добавка", None))
        self.editzerno.setText(_translate("Dialog_Korm", "0", None))
        self.groupBox_3.setTitle(_translate("Dialog_Korm", "Новый комбикорм", None))
        self.btnaddzerno_2.setText(_translate("Dialog_Korm", "Добавить", None))
        self.editdobavka_2.setText(_translate("Dialog_Korm", "0", None))
        self.btnaddmaslo_2.setText(_translate("Dialog_Korm", "Добавить", None))
        self.label_2.setText(_translate("Dialog_Korm", "Масло", None))
        self.label_7.setText(_translate("Dialog_Korm", "Зерно", None))
        self.btnadddobavka_2.setText(_translate("Dialog_Korm", "Добавить", None))
        self.editMaslo_2.setText(_translate("Dialog_Korm", "0", None))
        self.cancelbtn_2.setText(_translate("Dialog_Korm", "Отмена", None))
        self.label_8.setText(_translate("Dialog_Korm", "Название нового комбикорма", None))
        self.okbtn_2.setText(_translate("Dialog_Korm", "Применить", None))
        self.label_9.setText(_translate("Dialog_Korm", "Ингридиенты", None))
        self.label_10.setText(_translate("Dialog_Korm", "Добавка", None))
        self.editzerno_2.setText(_translate("Dialog_Korm", "0", None))
        self.groupBox_4.setTitle(_translate("Dialog_Korm", "Расположение готового комбикорма", None))
        self.label_11.setText(_translate("Dialog_Korm", "Банка 4", None))
        self.label_15.setText(_translate("Dialog_Korm", "Банка 3", None))
        self.label_16.setText(_translate("Dialog_Korm", "Банка 1", None))
        self.label_12.setText(_translate("Dialog_Korm", "Банка 2", None))
        self.label_14.setText(_translate("Dialog_Korm", "Банка 6", None))
        self.label_13.setText(_translate("Dialog_Korm", "Банка 5", None))

