# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_zerno.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog_Zerno(object):
    def setupUi(self, Dialog_Zerno):
        Dialog_Zerno.setObjectName(_fromUtf8("Dialog_Zerno"))
        Dialog_Zerno.resize(1333, 669)
        self.groupBox = QtGui.QGroupBox(Dialog_Zerno)
        self.groupBox.setGeometry(QtCore.QRect(10, 330, 1321, 331))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 10, 221, 19))
        self.label.setObjectName(_fromUtf8("label"))
        self.okbtn = QtGui.QPushButton(self.groupBox)
        self.okbtn.setGeometry(QtCore.QRect(130, 60, 112, 34))
        self.okbtn.setObjectName(_fromUtf8("okbtn"))
        self.cancelbtn = QtGui.QPushButton(self.groupBox)
        self.cancelbtn.setGeometry(QtCore.QRect(20, 60, 112, 34))
        self.cancelbtn.setObjectName(_fromUtf8("cancelbtn"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(20, 30, 221, 25))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.comboBox_1 = QtGui.QComboBox(self.groupBox)
        self.comboBox_1.setGeometry(QtCore.QRect(392, 18, 231, 22))
        self.comboBox_1.setObjectName(_fromUtf8("comboBox_1"))
        self.comboBox_2 = QtGui.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(392, 48, 231, 22))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_3 = QtGui.QComboBox(self.groupBox)
        self.comboBox_3.setGeometry(QtCore.QRect(392, 78, 231, 22))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_4 = QtGui.QComboBox(self.groupBox)
        self.comboBox_4.setGeometry(QtCore.QRect(392, 108, 231, 22))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_5 = QtGui.QComboBox(self.groupBox)
        self.comboBox_5.setGeometry(QtCore.QRect(392, 138, 231, 22))
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_6 = QtGui.QComboBox(self.groupBox)
        self.comboBox_6.setGeometry(QtCore.QRect(392, 168, 231, 22))
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_7 = QtGui.QComboBox(self.groupBox)
        self.comboBox_7.setGeometry(QtCore.QRect(392, 198, 231, 22))
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.comboBox_8 = QtGui.QComboBox(self.groupBox)
        self.comboBox_8.setGeometry(QtCore.QRect(392, 228, 231, 22))
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.comboBox_9 = QtGui.QComboBox(self.groupBox)
        self.comboBox_9.setGeometry(QtCore.QRect(392, 258, 231, 22))
        self.comboBox_9.setObjectName(_fromUtf8("comboBox_9"))
        self.comboBox_10 = QtGui.QComboBox(self.groupBox)
        self.comboBox_10.setGeometry(QtCore.QRect(392, 288, 231, 22))
        self.comboBox_10.setObjectName(_fromUtf8("comboBox_10"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(332, 28, 46, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(332, 58, 46, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(332, 88, 46, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(332, 118, 46, 13))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(332, 148, 46, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(332, 178, 46, 13))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(332, 208, 46, 13))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(332, 238, 46, 13))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(332, 268, 46, 13))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(332, 298, 46, 13))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.groupBox_2 = QtGui.QGroupBox(Dialog_Zerno)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 1321, 331))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.banka1 = QtGui.QLabel(self.groupBox_2)
        self.banka1.setGeometry(QtCore.QRect(30, 81, 41, 171))
        self.banka1.setText(_fromUtf8(""))
        self.banka1.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.banka1.setObjectName(_fromUtf8("banka1"))
        self.banka2 = QtGui.QLabel(self.groupBox_2)
        self.banka2.setGeometry(QtCore.QRect(160, 81, 41, 171))
        self.banka2.setText(_fromUtf8(""))
        self.banka2.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.banka2.setObjectName(_fromUtf8("banka2"))
        self.banka3 = QtGui.QLabel(self.groupBox_2)
        self.banka3.setGeometry(QtCore.QRect(290, 86, 41, 161))
        self.banka3.setText(_fromUtf8(""))
        self.banka3.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.banka3.setObjectName(_fromUtf8("banka3"))
        self.banka4 = QtGui.QLabel(self.groupBox_2)
        self.banka4.setGeometry(QtCore.QRect(420, 81, 41, 171))
        self.banka4.setText(_fromUtf8(""))
        self.banka4.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.banka4.setObjectName(_fromUtf8("banka4"))
        self.banka5 = QtGui.QLabel(self.groupBox_2)
        self.banka5.setGeometry(QtCore.QRect(550, 81, 41, 171))
        self.banka5.setText(_fromUtf8(""))
        self.banka5.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.banka5.setObjectName(_fromUtf8("banka5"))
        self.banka6 = QtGui.QLabel(self.groupBox_2)
        self.banka6.setGeometry(QtCore.QRect(670, 86, 41, 161))
        self.banka6.setText(_fromUtf8(""))
        self.banka6.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.banka6.setObjectName(_fromUtf8("banka6"))
        self.banka7 = QtGui.QLabel(self.groupBox_2)
        self.banka7.setGeometry(QtCore.QRect(800, 91, 41, 151))
        self.banka7.setText(_fromUtf8(""))
        self.banka7.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.banka7.setObjectName(_fromUtf8("banka7"))
        self.banka8 = QtGui.QLabel(self.groupBox_2)
        self.banka8.setGeometry(QtCore.QRect(930, 91, 41, 151))
        self.banka8.setText(_fromUtf8(""))
        self.banka8.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.banka8.setObjectName(_fromUtf8("banka8"))
        self.banka9 = QtGui.QLabel(self.groupBox_2)
        self.banka9.setGeometry(QtCore.QRect(1060, 91, 41, 151))
        self.banka9.setText(_fromUtf8(""))
        self.banka9.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.banka9.setObjectName(_fromUtf8("banka9"))
        self.banka10 = QtGui.QLabel(self.groupBox_2)
        self.banka10.setGeometry(QtCore.QRect(1190, 91, 41, 151))
        self.banka10.setText(_fromUtf8(""))
        self.banka10.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.banka10.setObjectName(_fromUtf8("banka10"))
        self.savebankabtn = QtGui.QPushButton(self.groupBox_2)
        self.savebankabtn.setGeometry(QtCore.QRect(680, 270, 112, 34))
        self.savebankabtn.setObjectName(_fromUtf8("savebankabtn"))
        self.labelbanka1 = QtGui.QLabel(self.groupBox_2)
        self.labelbanka1.setGeometry(QtCore.QRect(30, 70, 81, 16))
        self.labelbanka1.setObjectName(_fromUtf8("labelbanka1"))
        self.labelbanka2 = QtGui.QLabel(self.groupBox_2)
        self.labelbanka2.setGeometry(QtCore.QRect(160, 70, 81, 16))
        self.labelbanka2.setObjectName(_fromUtf8("labelbanka2"))
        self.labelbanka3 = QtGui.QLabel(self.groupBox_2)
        self.labelbanka3.setGeometry(QtCore.QRect(290, 69, 91, 16))
        self.labelbanka3.setObjectName(_fromUtf8("labelbanka3"))
        self.labelbanka4 = QtGui.QLabel(self.groupBox_2)
        self.labelbanka4.setGeometry(QtCore.QRect(420, 68, 91, 16))
        self.labelbanka4.setObjectName(_fromUtf8("labelbanka4"))
        self.labelbanka5 = QtGui.QLabel(self.groupBox_2)
        self.labelbanka5.setGeometry(QtCore.QRect(550, 68, 101, 16))
        self.labelbanka5.setObjectName(_fromUtf8("labelbanka5"))
        self.labelbanka6 = QtGui.QLabel(self.groupBox_2)
        self.labelbanka6.setGeometry(QtCore.QRect(670, 68, 81, 16))
        self.labelbanka6.setObjectName(_fromUtf8("labelbanka6"))
        self.labelbanka7 = QtGui.QLabel(self.groupBox_2)
        self.labelbanka7.setGeometry(QtCore.QRect(800, 68, 81, 16))
        self.labelbanka7.setObjectName(_fromUtf8("labelbanka7"))
        self.labelbanka8 = QtGui.QLabel(self.groupBox_2)
        self.labelbanka8.setGeometry(QtCore.QRect(930, 69, 81, 16))
        self.labelbanka8.setObjectName(_fromUtf8("labelbanka8"))
        self.labelbanka9 = QtGui.QLabel(self.groupBox_2)
        self.labelbanka9.setGeometry(QtCore.QRect(1060, 69, 81, 20))
        self.labelbanka9.setObjectName(_fromUtf8("labelbanka9"))
        self.labelbanka10 = QtGui.QLabel(self.groupBox_2)
        self.labelbanka10.setGeometry(QtCore.QRect(1190, 69, 81, 20))
        self.labelbanka10.setObjectName(_fromUtf8("labelbanka10"))
        self.labelbanka10_2 = QtGui.QLabel(self.groupBox_2)
        self.labelbanka10_2.setGeometry(QtCore.QRect(1194, 142, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.labelbanka10_2.setFont(font)
        self.labelbanka10_2.setObjectName(_fromUtf8("labelbanka10_2"))
        self.labelbanka6_2 = QtGui.QLabel(self.groupBox_2)
        self.labelbanka6_2.setGeometry(QtCore.QRect(684, 141, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.labelbanka6_2.setFont(font)
        self.labelbanka6_2.setObjectName(_fromUtf8("labelbanka6_2"))
        self.labelbanka5_2 = QtGui.QLabel(self.groupBox_2)
        self.labelbanka5_2.setGeometry(QtCore.QRect(564, 141, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.labelbanka5_2.setFont(font)
        self.labelbanka5_2.setObjectName(_fromUtf8("labelbanka5_2"))
        self.labelbanka8_2 = QtGui.QLabel(self.groupBox_2)
        self.labelbanka8_2.setGeometry(QtCore.QRect(944, 142, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.labelbanka8_2.setFont(font)
        self.labelbanka8_2.setObjectName(_fromUtf8("labelbanka8_2"))
        self.labelbanka1_2 = QtGui.QLabel(self.groupBox_2)
        self.labelbanka1_2.setGeometry(QtCore.QRect(44, 139, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.labelbanka1_2.setFont(font)
        self.labelbanka1_2.setObjectName(_fromUtf8("labelbanka1_2"))
        self.labelbanka4_2 = QtGui.QLabel(self.groupBox_2)
        self.labelbanka4_2.setGeometry(QtCore.QRect(434, 141, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.labelbanka4_2.setFont(font)
        self.labelbanka4_2.setObjectName(_fromUtf8("labelbanka4_2"))
        self.labelbanka2_2 = QtGui.QLabel(self.groupBox_2)
        self.labelbanka2_2.setGeometry(QtCore.QRect(174, 139, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.labelbanka2_2.setFont(font)
        self.labelbanka2_2.setObjectName(_fromUtf8("labelbanka2_2"))
        self.labelbanka3_2 = QtGui.QLabel(self.groupBox_2)
        self.labelbanka3_2.setGeometry(QtCore.QRect(304, 141, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.labelbanka3_2.setFont(font)
        self.labelbanka3_2.setObjectName(_fromUtf8("labelbanka3_2"))
        self.labelbanka9_2 = QtGui.QLabel(self.groupBox_2)
        self.labelbanka9_2.setGeometry(QtCore.QRect(1074, 142, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.labelbanka9_2.setFont(font)
        self.labelbanka9_2.setObjectName(_fromUtf8("labelbanka9_2"))
        self.labelbanka7_2 = QtGui.QLabel(self.groupBox_2)
        self.labelbanka7_2.setGeometry(QtCore.QRect(814, 141, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.labelbanka7_2.setFont(font)
        self.labelbanka7_2.setObjectName(_fromUtf8("labelbanka7_2"))

        self.retranslateUi(Dialog_Zerno)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Zerno)

    def retranslateUi(self, Dialog_Zerno):
        Dialog_Zerno.setWindowTitle(_translate("Dialog_Zerno", "Dialog", None))
        self.groupBox.setTitle(_translate("Dialog_Zerno", "Новое зерно", None))
        self.label.setText(_translate("Dialog_Zerno", "Наименование нового зерна", None))
        self.okbtn.setText(_translate("Dialog_Zerno", "Добавить", None))
        self.cancelbtn.setText(_translate("Dialog_Zerno", "Отмена", None))
        self.label_2.setText(_translate("Dialog_Zerno", "Банка 1", None))
        self.label_3.setText(_translate("Dialog_Zerno", "Банка 2", None))
        self.label_4.setText(_translate("Dialog_Zerno", "Банка 3", None))
        self.label_5.setText(_translate("Dialog_Zerno", "Банка 4", None))
        self.label_6.setText(_translate("Dialog_Zerno", "Банка 5", None))
        self.label_7.setText(_translate("Dialog_Zerno", "Банка 6", None))
        self.label_8.setText(_translate("Dialog_Zerno", "Банка 7", None))
        self.label_9.setText(_translate("Dialog_Zerno", "Банка 8", None))
        self.label_10.setText(_translate("Dialog_Zerno", "Банка 9", None))
        self.label_11.setText(_translate("Dialog_Zerno", "Банка 10", None))
        self.groupBox_2.setTitle(_translate("Dialog_Zerno", "Банки", None))
        self.savebankabtn.setText(_translate("Dialog_Zerno", "Применить", None))
        self.labelbanka1.setText(_translate("Dialog_Zerno", "TextLabel", None))
        self.labelbanka2.setText(_translate("Dialog_Zerno", "TextLabel", None))
        self.labelbanka3.setText(_translate("Dialog_Zerno", "TextLabel", None))
        self.labelbanka4.setText(_translate("Dialog_Zerno", "TextLabel", None))
        self.labelbanka5.setText(_translate("Dialog_Zerno", "TextLabel", None))
        self.labelbanka6.setText(_translate("Dialog_Zerno", "TextLabel", None))
        self.labelbanka7.setText(_translate("Dialog_Zerno", "TextLabel", None))
        self.labelbanka8.setText(_translate("Dialog_Zerno", "TextLabel", None))
        self.labelbanka9.setText(_translate("Dialog_Zerno", "TextLabel", None))
        self.labelbanka10.setText(_translate("Dialog_Zerno", "TextLabel", None))
        self.labelbanka10_2.setText(_translate("Dialog_Zerno", "10", None))
        self.labelbanka6_2.setText(_translate("Dialog_Zerno", "6", None))
        self.labelbanka5_2.setText(_translate("Dialog_Zerno", "5", None))
        self.labelbanka8_2.setText(_translate("Dialog_Zerno", "8", None))
        self.labelbanka1_2.setText(_translate("Dialog_Zerno", "1", None))
        self.labelbanka4_2.setText(_translate("Dialog_Zerno", "4", None))
        self.labelbanka2_2.setText(_translate("Dialog_Zerno", "2", None))
        self.labelbanka3_2.setText(_translate("Dialog_Zerno", "3", None))
        self.labelbanka9_2.setText(_translate("Dialog_Zerno", "9", None))
        self.labelbanka7_2.setText(_translate("Dialog_Zerno", "7", None))

