# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogreceptunited.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog_recept(object):
    def setupUi(self, Dialog_recept):
        Dialog_recept.setObjectName(_fromUtf8("Dialog_recept"))
        Dialog_recept.resize(759, 388)
        self.groupBox_6 = QtGui.QGroupBox(Dialog_recept)
        self.groupBox_6.setGeometry(QtCore.QRect(598, 0, 161, 201))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_4.setGeometry(QtCore.QRect(83, 152, 71, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit.setGeometry(QtCore.QRect(5, 37, 151, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.pushButton = QtGui.QPushButton(self.groupBox_6)
        self.pushButton.setGeometry(QtCore.QRect(5, 57, 81, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.comboBox = QtGui.QComboBox(self.groupBox_6)
        self.comboBox.setGeometry(QtCore.QRect(6, 127, 151, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_3.setGeometry(QtCore.QRect(6, 152, 81, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.label = QtGui.QLabel(self.groupBox_6)
        self.label.setGeometry(QtCore.QRect(5, 17, 161, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox_6)
        self.label_2.setGeometry(QtCore.QRect(6, 107, 161, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_2.setGeometry(QtCore.QRect(85, 57, 71, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.groupBox_5 = QtGui.QGroupBox(Dialog_recept)
        self.groupBox_5.setGeometry(QtCore.QRect(378, 200, 81, 181))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.maslo_2 = QtGui.QLabel(self.groupBox_5)
        self.maslo_2.setGeometry(QtCore.QRect(21, 49, 41, 81))
        self.maslo_2.setText(_fromUtf8(""))
        self.maslo_2.setPixmap(QtGui.QPixmap(_fromUtf8("maslobochka.png")))
        self.maslo_2.setObjectName(_fromUtf8("maslo_2"))
        self.masloedit_2 = QtGui.QLineEdit(self.groupBox_5)
        self.masloedit_2.setGeometry(QtCore.QRect(21, 69, 41, 20))
        self.masloedit_2.setObjectName(_fromUtf8("masloedit_2"))
        self.groupBox_3 = QtGui.QGroupBox(Dialog_recept)
        self.groupBox_3.setGeometry(QtCore.QRect(458, 200, 301, 181))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(17, 74, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(167, 74, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.siloskorm1 = QtGui.QLabel(self.groupBox_3)
        self.siloskorm1.setGeometry(QtCore.QRect(5, 19, 41, 151))
        self.siloskorm1.setText(_fromUtf8(""))
        self.siloskorm1.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.siloskorm1.setObjectName(_fromUtf8("siloskorm1"))
        self.siloskorm2 = QtGui.QLabel(self.groupBox_3)
        self.siloskorm2.setGeometry(QtCore.QRect(55, 18, 41, 151))
        self.siloskorm2.setText(_fromUtf8(""))
        self.siloskorm2.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.siloskorm2.setObjectName(_fromUtf8("siloskorm2"))
        self.siloskorm5 = QtGui.QLabel(self.groupBox_3)
        self.siloskorm5.setGeometry(QtCore.QRect(205, 18, 41, 151))
        self.siloskorm5.setText(_fromUtf8(""))
        self.siloskorm5.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.siloskorm5.setObjectName(_fromUtf8("siloskorm5"))
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(117, 74, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(217, 74, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.siloskorm3 = QtGui.QLabel(self.groupBox_3)
        self.siloskorm3.setGeometry(QtCore.QRect(105, 18, 41, 151))
        self.siloskorm3.setText(_fromUtf8(""))
        self.siloskorm3.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.siloskorm3.setObjectName(_fromUtf8("siloskorm3"))
        self.siloskorm6 = QtGui.QLabel(self.groupBox_3)
        self.siloskorm6.setGeometry(QtCore.QRect(255, 18, 41, 151))
        self.siloskorm6.setText(_fromUtf8(""))
        self.siloskorm6.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.siloskorm6.setObjectName(_fromUtf8("siloskorm6"))
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(267, 74, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(67, 74, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.siloskorm4 = QtGui.QLabel(self.groupBox_3)
        self.siloskorm4.setGeometry(QtCore.QRect(155, 18, 41, 151))
        self.siloskorm4.setText(_fromUtf8(""))
        self.siloskorm4.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.siloskorm4.setObjectName(_fromUtf8("siloskorm4"))
        self.siloskorm1.raise_()
        self.siloskorm2.raise_()
        self.siloskorm5.raise_()
        self.label_10.raise_()
        self.siloskorm3.raise_()
        self.siloskorm6.raise_()
        self.label_11.raise_()
        self.label_13.raise_()
        self.siloskorm4.raise_()
        self.label_12.raise_()
        self.label_14.raise_()
        self.label_9.raise_()
        self.groupBox = QtGui.QGroupBox(Dialog_recept)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 601, 201))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.zernosilos_10 = QtGui.QLabel(self.groupBox)
        self.zernosilos_10.setGeometry(QtCore.QRect(550, 10, 51, 161))
        self.zernosilos_10.setText(_fromUtf8(""))
        self.zernosilos_10.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.zernosilos_10.setObjectName(_fromUtf8("zernosilos_10"))
        self.zernosilos_3 = QtGui.QLabel(self.groupBox)
        self.zernosilos_3.setGeometry(QtCore.QRect(130, 10, 51, 161))
        self.zernosilos_3.setText(_fromUtf8(""))
        self.zernosilos_3.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.zernosilos_3.setObjectName(_fromUtf8("zernosilos_3"))
        self.zernosilos = QtGui.QLabel(self.groupBox)
        self.zernosilos.setGeometry(QtCore.QRect(10, 10, 51, 161))
        self.zernosilos.setText(_fromUtf8(""))
        self.zernosilos.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.zernosilos.setObjectName(_fromUtf8("zernosilos"))
        self.zernosilos_2 = QtGui.QLabel(self.groupBox)
        self.zernosilos_2.setGeometry(QtCore.QRect(70, 10, 51, 161))
        self.zernosilos_2.setText(_fromUtf8(""))
        self.zernosilos_2.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.zernosilos_2.setObjectName(_fromUtf8("zernosilos_2"))
        self.zernosilos_9 = QtGui.QLabel(self.groupBox)
        self.zernosilos_9.setGeometry(QtCore.QRect(370, 10, 51, 161))
        self.zernosilos_9.setText(_fromUtf8(""))
        self.zernosilos_9.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.zernosilos_9.setObjectName(_fromUtf8("zernosilos_9"))
        self.zernosilos_4 = QtGui.QLabel(self.groupBox)
        self.zernosilos_4.setGeometry(QtCore.QRect(310, 10, 51, 161))
        self.zernosilos_4.setText(_fromUtf8(""))
        self.zernosilos_4.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.zernosilos_4.setObjectName(_fromUtf8("zernosilos_4"))
        self.zernosilos_5 = QtGui.QLabel(self.groupBox)
        self.zernosilos_5.setGeometry(QtCore.QRect(190, 10, 51, 161))
        self.zernosilos_5.setText(_fromUtf8(""))
        self.zernosilos_5.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.zernosilos_5.setObjectName(_fromUtf8("zernosilos_5"))
        self.zernosilos_7 = QtGui.QLabel(self.groupBox)
        self.zernosilos_7.setGeometry(QtCore.QRect(430, 10, 51, 161))
        self.zernosilos_7.setText(_fromUtf8(""))
        self.zernosilos_7.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.zernosilos_7.setObjectName(_fromUtf8("zernosilos_7"))
        self.zernosilos_6 = QtGui.QLabel(self.groupBox)
        self.zernosilos_6.setGeometry(QtCore.QRect(250, 10, 51, 161))
        self.zernosilos_6.setText(_fromUtf8(""))
        self.zernosilos_6.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.zernosilos_6.setObjectName(_fromUtf8("zernosilos_6"))
        self.zernoedit1 = QtGui.QLineEdit(self.groupBox)
        self.zernoedit1.setGeometry(QtCore.QRect(10, 70, 41, 20))
        self.zernoedit1.setObjectName(_fromUtf8("zernoedit1"))
        self.zernoedit2 = QtGui.QLineEdit(self.groupBox)
        self.zernoedit2.setGeometry(QtCore.QRect(70, 70, 41, 20))
        self.zernoedit2.setObjectName(_fromUtf8("zernoedit2"))
        self.zernoedit3 = QtGui.QLineEdit(self.groupBox)
        self.zernoedit3.setGeometry(QtCore.QRect(130, 70, 41, 20))
        self.zernoedit3.setObjectName(_fromUtf8("zernoedit3"))
        self.zernoedit4 = QtGui.QLineEdit(self.groupBox)
        self.zernoedit4.setGeometry(QtCore.QRect(190, 70, 41, 20))
        self.zernoedit4.setObjectName(_fromUtf8("zernoedit4"))
        self.zernoedit5 = QtGui.QLineEdit(self.groupBox)
        self.zernoedit5.setGeometry(QtCore.QRect(250, 70, 41, 20))
        self.zernoedit5.setObjectName(_fromUtf8("zernoedit5"))
        self.zernoedit6 = QtGui.QLineEdit(self.groupBox)
        self.zernoedit6.setGeometry(QtCore.QRect(310, 70, 41, 20))
        self.zernoedit6.setObjectName(_fromUtf8("zernoedit6"))
        self.zernoedit7 = QtGui.QLineEdit(self.groupBox)
        self.zernoedit7.setGeometry(QtCore.QRect(370, 70, 41, 20))
        self.zernoedit7.setObjectName(_fromUtf8("zernoedit7"))
        self.zernoedit8 = QtGui.QLineEdit(self.groupBox)
        self.zernoedit8.setGeometry(QtCore.QRect(430, 70, 41, 20))
        self.zernoedit8.setObjectName(_fromUtf8("zernoedit8"))
        self.zernoedit9 = QtGui.QLineEdit(self.groupBox)
        self.zernoedit9.setGeometry(QtCore.QRect(490, 70, 41, 20))
        self.zernoedit9.setObjectName(_fromUtf8("zernoedit9"))
        self.zernoedit10 = QtGui.QLineEdit(self.groupBox)
        self.zernoedit10.setGeometry(QtCore.QRect(550, 70, 41, 20))
        self.zernoedit10.setObjectName(_fromUtf8("zernoedit10"))
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(323, 30, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(203, 30, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(20, 30, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(143, 30, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(263, 30, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(85, 30, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.zernosilos_11 = QtGui.QLabel(self.groupBox)
        self.zernosilos_11.setGeometry(QtCore.QRect(490, 10, 51, 161))
        self.zernosilos_11.setText(_fromUtf8(""))
        self.zernosilos_11.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.zernosilos_11.setObjectName(_fromUtf8("zernosilos_11"))
        self.label_21 = QtGui.QLabel(self.groupBox)
        self.label_21.setGeometry(QtCore.QRect(556, 29, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(444, 30, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.groupBox)
        self.label_23.setGeometry(QtCore.QRect(506, 30, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.groupBox)
        self.label_24.setGeometry(QtCore.QRect(387, 30, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.zernosilos_11.raise_()
        self.zernosilos_10.raise_()
        self.zernosilos_3.raise_()
        self.zernosilos.raise_()
        self.zernosilos_2.raise_()
        self.zernosilos_9.raise_()
        self.zernosilos_4.raise_()
        self.zernosilos_5.raise_()
        self.zernosilos_7.raise_()
        self.zernosilos_6.raise_()
        self.zernoedit1.raise_()
        self.zernoedit2.raise_()
        self.zernoedit3.raise_()
        self.zernoedit4.raise_()
        self.zernoedit5.raise_()
        self.zernoedit6.raise_()
        self.zernoedit7.raise_()
        self.zernoedit8.raise_()
        self.zernoedit9.raise_()
        self.zernoedit10.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.groupBox_4 = QtGui.QGroupBox(Dialog_recept)
        self.groupBox_4.setGeometry(QtCore.QRect(300, 200, 81, 181))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.maslo = QtGui.QLabel(self.groupBox_4)
        self.maslo.setGeometry(QtCore.QRect(20, 50, 41, 81))
        self.maslo.setText(_fromUtf8(""))
        self.maslo.setPixmap(QtGui.QPixmap(_fromUtf8("maslobochka.png")))
        self.maslo.setObjectName(_fromUtf8("maslo"))
        self.masloedit = QtGui.QLineEdit(self.groupBox_4)
        self.masloedit.setGeometry(QtCore.QRect(20, 70, 41, 20))
        self.masloedit.setObjectName(_fromUtf8("masloedit"))
        self.groupBox_2 = QtGui.QGroupBox(Dialog_recept)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 200, 301, 181))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.dobavka4 = QtGui.QLabel(self.groupBox_2)
        self.dobavka4.setGeometry(QtCore.QRect(154, 40, 41, 101))
        self.dobavka4.setText(_fromUtf8(""))
        self.dobavka4.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.dobavka4.setScaledContents(True)
        self.dobavka4.setObjectName(_fromUtf8("dobavka4"))
        self.dobavka2 = QtGui.QLabel(self.groupBox_2)
        self.dobavka2.setGeometry(QtCore.QRect(54, 40, 41, 101))
        self.dobavka2.setText(_fromUtf8(""))
        self.dobavka2.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.dobavka2.setScaledContents(True)
        self.dobavka2.setObjectName(_fromUtf8("dobavka2"))
        self.dobavka5 = QtGui.QLabel(self.groupBox_2)
        self.dobavka5.setGeometry(QtCore.QRect(204, 40, 41, 101))
        self.dobavka5.setText(_fromUtf8(""))
        self.dobavka5.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.dobavka5.setScaledContents(True)
        self.dobavka5.setObjectName(_fromUtf8("dobavka5"))
        self.dobavka6 = QtGui.QLabel(self.groupBox_2)
        self.dobavka6.setGeometry(QtCore.QRect(254, 40, 41, 101))
        self.dobavka6.setText(_fromUtf8(""))
        self.dobavka6.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.dobavka6.setScaledContents(True)
        self.dobavka6.setObjectName(_fromUtf8("dobavka6"))
        self.dobavka3 = QtGui.QLabel(self.groupBox_2)
        self.dobavka3.setGeometry(QtCore.QRect(104, 40, 41, 101))
        self.dobavka3.setText(_fromUtf8(""))
        self.dobavka3.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.dobavka3.setScaledContents(True)
        self.dobavka3.setObjectName(_fromUtf8("dobavka3"))
        self.dobavka1 = QtGui.QLabel(self.groupBox_2)
        self.dobavka1.setGeometry(QtCore.QRect(4, 40, 41, 101))
        self.dobavka1.setText(_fromUtf8(""))
        self.dobavka1.setPixmap(QtGui.QPixmap(_fromUtf8("silos.png")))
        self.dobavka1.setScaledContents(True)
        self.dobavka1.setObjectName(_fromUtf8("dobavka1"))
        self.dobavkaedit1 = QtGui.QLineEdit(self.groupBox_2)
        self.dobavkaedit1.setGeometry(QtCore.QRect(3, 88, 41, 20))
        self.dobavkaedit1.setObjectName(_fromUtf8("dobavkaedit1"))
        self.dobavkaedit1_2 = QtGui.QLineEdit(self.groupBox_2)
        self.dobavkaedit1_2.setGeometry(QtCore.QRect(53, 88, 41, 20))
        self.dobavkaedit1_2.setObjectName(_fromUtf8("dobavkaedit1_2"))
        self.dobavkaedit1_3 = QtGui.QLineEdit(self.groupBox_2)
        self.dobavkaedit1_3.setGeometry(QtCore.QRect(103, 88, 41, 20))
        self.dobavkaedit1_3.setObjectName(_fromUtf8("dobavkaedit1_3"))
        self.dobavkaedit1_4 = QtGui.QLineEdit(self.groupBox_2)
        self.dobavkaedit1_4.setGeometry(QtCore.QRect(153, 88, 41, 20))
        self.dobavkaedit1_4.setObjectName(_fromUtf8("dobavkaedit1_4"))
        self.dobavkaedit1_5 = QtGui.QLineEdit(self.groupBox_2)
        self.dobavkaedit1_5.setGeometry(QtCore.QRect(203, 88, 41, 20))
        self.dobavkaedit1_5.setObjectName(_fromUtf8("dobavkaedit1_5"))
        self.dobavkaedit1_6 = QtGui.QLineEdit(self.groupBox_2)
        self.dobavkaedit1_6.setGeometry(QtCore.QRect(253, 88, 41, 20))
        self.dobavkaedit1_6.setObjectName(_fromUtf8("dobavkaedit1_6"))
        self.label_25 = QtGui.QLabel(self.groupBox_2)
        self.label_25.setGeometry(QtCore.QRect(270, 52, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.groupBox_2)
        self.label_26.setGeometry(QtCore.QRect(170, 52, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.groupBox_2)
        self.label_27.setGeometry(QtCore.QRect(20, 52, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.groupBox_2)
        self.label_28.setGeometry(QtCore.QRect(120, 52, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.groupBox_2)
        self.label_29.setGeometry(QtCore.QRect(220, 52, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.groupBox_2)
        self.label_30.setGeometry(QtCore.QRect(70, 52, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))

        self.retranslateUi(Dialog_recept)
        QtCore.QMetaObject.connectSlotsByName(Dialog_recept)

    def retranslateUi(self, Dialog_recept):
        Dialog_recept.setWindowTitle(_translate("Dialog_recept", "Dialog", None))
        self.groupBox_6.setTitle(_translate("Dialog_recept", "Рецепт", None))
        self.pushButton_4.setText(_translate("Dialog_recept", "Удалить", None))
        self.pushButton.setText(_translate("Dialog_recept", "Очистить", None))
        self.pushButton_3.setText(_translate("Dialog_recept", "Изменить", None))
        self.label.setText(_translate("Dialog_recept", "Название нового комбикорма", None))
        self.label_2.setText(_translate("Dialog_recept", "Существующий комбикорм", None))
        self.pushButton_2.setText(_translate("Dialog_recept", "Добавить", None))
        self.groupBox_5.setTitle(_translate("Dialog_recept", "Лекарство", None))
        self.masloedit_2.setText(_translate("Dialog_recept", "0", None))
        self.groupBox_3.setTitle(_translate("Dialog_recept", "Комбикорм (Выбор банки для выгрузки)", None))
        self.label_14.setText(_translate("Dialog_recept", "1", None))
        self.label_9.setText(_translate("Dialog_recept", "4", None))
        self.label_12.setText(_translate("Dialog_recept", "3", None))
        self.label_10.setText(_translate("Dialog_recept", "5", None))
        self.label_11.setText(_translate("Dialog_recept", "6", None))
        self.label_13.setText(_translate("Dialog_recept", "2", None))
        self.groupBox.setTitle(_translate("Dialog_recept", "Зерно", None))
        self.zernoedit1.setText(_translate("Dialog_recept", "0", None))
        self.zernoedit2.setText(_translate("Dialog_recept", "0", None))
        self.zernoedit3.setText(_translate("Dialog_recept", "0", None))
        self.zernoedit4.setText(_translate("Dialog_recept", "0", None))
        self.zernoedit5.setText(_translate("Dialog_recept", "0", None))
        self.zernoedit6.setText(_translate("Dialog_recept", "0", None))
        self.zernoedit7.setText(_translate("Dialog_recept", "0", None))
        self.zernoedit8.setText(_translate("Dialog_recept", "0", None))
        self.zernoedit9.setText(_translate("Dialog_recept", "0", None))
        self.label_15.setText(_translate("Dialog_recept", "6", None))
        self.label_16.setText(_translate("Dialog_recept", "4", None))
        self.label_17.setText(_translate("Dialog_recept", "1", None))
        self.label_18.setText(_translate("Dialog_recept", "3", None))
        self.label_19.setText(_translate("Dialog_recept", "5", None))
        self.label_20.setText(_translate("Dialog_recept", "2", None))
        self.label_21.setText(_translate("Dialog_recept", "10", None))
        self.label_22.setText(_translate("Dialog_recept", "8", None))
        self.label_23.setText(_translate("Dialog_recept", "9", None))
        self.label_24.setText(_translate("Dialog_recept", "7", None))
        self.groupBox_4.setTitle(_translate("Dialog_recept", "Масло ", None))
        self.masloedit.setText(_translate("Dialog_recept", "0", None))
        self.groupBox_2.setTitle(_translate("Dialog_recept", "Добавки", None))
        self.dobavkaedit1.setText(_translate("Dialog_recept", "0", None))
        self.dobavkaedit1_2.setText(_translate("Dialog_recept", "0", None))
        self.dobavkaedit1_3.setText(_translate("Dialog_recept", "0", None))
        self.dobavkaedit1_4.setText(_translate("Dialog_recept", "0", None))
        self.dobavkaedit1_5.setText(_translate("Dialog_recept", "0", None))
        self.dobavkaedit1_6.setText(_translate("Dialog_recept", "0", None))
        self.label_25.setText(_translate("Dialog_recept", "6", None))
        self.label_26.setText(_translate("Dialog_recept", "4", None))
        self.label_27.setText(_translate("Dialog_recept", "1", None))
        self.label_28.setText(_translate("Dialog_recept", "3", None))
        self.label_29.setText(_translate("Dialog_recept", "5", None))
        self.label_30.setText(_translate("Dialog_recept", "2", None))

